### ISSUE TITLE
“Label Based on Current Word…”. does not work

### ISSUE THREAD

**Issue by Bilalh** [textmate/latex.tmbundle#128]
“Label Based on Current Word…”. does not work. Error message as follows 

```
/Users/bilalh/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/latex.rb:117:in `label_names': wrong argument type Symbol (expected Proc) (TypeError)
	from /Users/bilalh/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/command.rb:267:in `insert_label'
	from Label Based on Current Word…:9
```

tex file used

```
\documentclass{article}

\begin{document}
	
\section{Test}
\label{sec:test}

\ref{}

\end{document}
```

![screen shot 2015-05-28 at 01 09 16](https://cloud.githubusercontent.com/assets/171602/7850167/42663678-04d6-11e5-9c38-66dcc5fac1b0.png)

**Comment by Bilalh** [comment]
Disabling Label Based on Current Word / Selection… and Citation Based on Current Word / Selection… made the completion  work
