### ISSUE TITLE
Typeset & View (PDF) error

### ISSUE THREAD

**Issue by PhilGeek** [textmate/latex.tmbundle#179]
Running MacTex on 10.14 and just installed TexMate 2. Typeset & View gives the following error:

Traceback (most recent call last): File "/Users/markkalderon/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/bin/texmate.py", line 957, in True if command in {'clean', 'version'} else False) File "/Users/markkalderon/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/bin/texmate.py", line 796, in get_typesetting_data typesetting_directives = find_tex_directives(filepath, ignore_warnings) File "/Users/markkalderon/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/lib/Python/tex.py", line 312, in find_tex_directives in enumerate(open(texfile, encoding=encoding)) IOError: [Errno 2] No such file or directory: '/Users/markelikalderon/Documents/Git/timaeus/timaeus.tex'

The file '/Users/markelikalderon/Documents/Git/timaeus/timaeus.tex' does exist.

I tried removing Bundle Modifications and Reverted to Defaults.

Any advice would be appreciated. Thanks in advance.

**Comment by sanssecours** [comment]
Hi Mark,

thank you for the bug report. Can you please provide [steps to reproduce the problem](https://github.com/textmate/bugs#writing-bug-reports)? The steps below show, how I tried to reproduce the issue.

1. Open “System Preferences”
2. Click on “Users & Groups” → “Guest User” → “Allow guests to log in to this computer”
3. Click on “Login Options” and enable fast user switching
4. Go to the menu bar
5. Click on the “User Switching Menu” (usually it just displays your current user name) and choose “Login Window…”
6. Login as user “Guest”
7. Open TextMate
8. Install the LaTeX bundle
9. Create a new file: <kbd>⌘</kbd>+<kbd>N</kbd>
10. Enter the following text

    ```tex
    \documentclass{article}

    \begin{document}
      Hello, World!
    \end{document}
    ```

11. Run “Typeset & View” (<kbd>⌘</kbd>+<kbd>R</kbd>)

After the last step TextMate shows a PDF containing the text “Hello, World!”. Can you please try, if the steps given above work for you? If they do, can you maybe provide a minimal version of your LateX source file that allow me to reproduce the problem?
