### ISSUE TITLE
Failure running "Typeset & View (pdf)"

### ISSUE THREAD

**Issue by kociak** [textmate/latex.tmbundle#194]
Hi
Trying to compile latex file leads to "Failure running "Typeset & View (pdf)", command returned status code" on Mac OS Monterey 12.5.1, MacBook Pro (13 inches, 2020, four ports Thunderbolt 3)

Steps to reproduce

- Open TextMate
- Install the latex bundle
- Create a new file: ⌘+N
- Enter the following text
 
```
\documentclass{article}

\begin{document}
  Hello, World!
\end{document}
```
- Run “Typeset & View” (⌘+R)

The following error message appears in a pop up window: "Failure running "Typeset & View (pdf)", command returned status code"
Attempting to close the typesetting window triggers a warning ("the job that the task is performing will not be completed")

using TexShop on the same file, same machine, does work perfectly.

**Comment by samfearn** [comment]
Having what seems like the same issue on a 2021 MacBook Pro running an M1Pro, and Ventura 13.2.1. I think this is also related to issues #188 possibly #179.

Running typeset and view on an unsaved MWE gives the following after prompting for a file save location:

    `Traceback (most recent call last): File "/Users/sam/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/bin/texmate.py", line 955, in typesetting_data = get_typesetting_data( File "/Users/sam/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/bin/texmate.py", line 795, in get_typesetting_data filepath = normpath(realpath(filepath)) File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/posixpath.py", line 390, in realpath filename = os.fspath(filename) TypeError: expected str, bytes or os.PathLike object, not NoneType`

and the popup error message: Command returned status code 1.

Running typeset and view again after the tex file has been previously saved, instead gives the following error:

    `The file /Users/sam/Dropbox/Mac (2)/Desktop/2untitled.pdf does not exist. 114:126: execution error: Skim got an error: AppleEvent timed out. (-1712)
Error 1 opening viewer

Command latexmk -pdf -f -r /tmp/latexmkrc -r '/Users/sam/Library/Application Support/TextMate/Managed/Bundles/LaTeX.tmbundle/Support/config/latexmkrc' 2untitled.tex exited with status 127`
